export const ERROR_CODES = {
	BAD_REQUEST: 'BAD_REQUEST',
	UNAUTHORIZED: 'UNAUTHORIZED',
	FORBIDDEN: 'FORBIDDEN',
	NOT_FOUND: 'NOT_FOUND',
	CONFLICT: 'CONFLICT',
	VALIDATION_FAILED: 'VALIDATION_FAILED',
	RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

	CRYPTO_INTEGRITY_ERROR: 'CRYPTO_INTEGRITY_ERROR',

	TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

	TOKEN_EXPIRED: 'TOKEN_EXPIRED',
	TOKEN_INVALID: 'TOKEN_INVALID',
	TOKEN_NOT_PROVIDED: 'TOKEN_NOT_PROVIDED',
	TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
	TOKEN_NOT_CREATED: 'TOKEN_NOT_CREATED',
	TOKEN_NOT_UPDATED: 'TOKEN_NOT_UPDATED',
	TOKEN_NOT_DELETED: 'TOKEN_NOT_DELETED',
	TOKEN_NOT_VALIDATED: 'TOKEN_NOT_VALIDATED',
	TOKEN_NOT_REFRESHED: 'TOKEN_NOT_REFRESHED',
	TOKEN_NOT_REVOKED: 'TOKEN_NOT_REVOKED',
	TOKEN_NOT_BLACKLISTED: 'TOKEN_NOT_BLACKLISTED',
	TOKEN_NOT_WHITELISTED: 'TOKEN_NOT_WHITELISTED',
	TOKEN_NOT_DECODED: 'TOKEN_NOT_DECODED',
	TOKEN_NOT_ENCODED: 'TOKEN_NOT_ENCODED',
	TOKEN_NOT_SIGNED: 'TOKEN_NOT_SIGNED',
	TOKEN_NOT_VERIFIED: 'TOKEN_NOT_VERIFIED',
	TOKEN_NOT_DECRYPTED: 'TOKEN_NOT_DECRYPTED',
	TOKEN_NOT_ENCRYPTED: 'TOKEN_NOT_ENCRYPTED',
	TOKEN_NOT_GENERATED: 'TOKEN_NOT_GENERATED',
} as const

export type ErrorCode = keyof typeof ERROR_CODES
